name: Testing hello-n.py

on: [push]

jobs:
  make-testing:
    name: Checking hello-n.py
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: "Installing Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
    
      - name: "Installing dependencies"
        run: python3 -m pip install -r requirements.txt
        shell: bash

      - name: Checking that hello-n.py prints "Hello, World!" n times
        run: |
diff <(cat <<EOF
How many times should I loop? Hello, World!
EOF) <(echo 1 | python3 src/hello-n.py)

diff <(cat <<EOF
How many times should I loop? Hello, World!
Hello, World!
Hello, World!
EOF) <(echo 3 | python3 src/hello-n.py)
        shell: bash
