name: Testing "Do you want to stop?"

on: [push]

jobs:
  make-testing:
    name: Checking do-you-want-to-stop.py
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: "Installing Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
    
      - name: Checking do-you-want-to-stop.py
        run: |
          diff <(cat <<EOF
          Do you want to stop? no
          Do you want to stop? no
          Do you want to stop? yes
          EOF) <(cat << EOF
          no
          no
          yes
          EOF) | python3 src/do-you-want-to-stop.py)
        shell: bash
