name: Testing Pattern

on: [push]

jobs:
  make-testing:
    name: Checking pattern.py
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: "Installing Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
    
      - name: Running pattern.py mean
        run: |
          diff <(echo 3.0) <(echo 1 2 3 4 5 | python3 src/lists.py mean)
        shell: bash

      - name: Running pattern.py times
        run: |
          diff <(echo 3 6 9 12 15) <(echo 1 2 3 4 5 | python3 src/lists.py times)
        shell: bash

      - name: Running pattern.py even
        run: |
          diff <(echo 2 4) <(echo 1 2 3 4 5 | python3 src/lists.py even)
        shell: bash
